### ISSUE TITLE
Python 2.6 support

### ISSUE THREAD

**Issue by jayvdb** [nigelsmall/httq#2]
There is at least one simple syntax issue with using httq on Python 2.6.

https://travis-ci.org/jayvdb/anyhttp/jobs/60478689

I didnt investigate further.

I dont mind a wontfix resolution, as I workaround it by excluding it from py2.6 builds 
(https://github.com/jayvdb/anyhttp/commit/34a3a79f2dc7d046b00c46b447c9166cf99bc20d) , and believe anyone using python 2.6 is crazy.

**Comment by technige** [comment]
Python 2.6 support has now been added.
